/**:
    ros__parameters:
        sensor_topic:
            lidar_topic: "points_raw"
            imu_topic: "imu_raw"

        slam_mode: 2 # 1: Mapping, 2: Localization

        lidar:
            # Velodyne_16, Velodyne_32, Velodyne_64, Ouster_128_os1,
            # LeiShen_16, RoboSense_16, Livox_Avia, Livox_Mid_360, None
            lidar_sensor_type: Velodyne_32
            lidar_point_time_scale: 1.0e-6
            lidar_point_jump_span: 6
            lidar_use_min_distance: 2.0
            lidar_use_max_distance: 1000.0
            lidar_rotation_noise_std: 0.001
            lidar_position_noise_std: 0.05

        imu:
            init_acc_bias: 0.0
            init_gyro_bias: 0.0
            acc_noise_std: 0.1
            gyro_noise_std: 0.01
            acc_rw_noise_std: 1.0e-5
            gyro_rw_noise_std: 1.0e-5
            has_orientation: false
            data_searcher_buffer_size: 2000

        gravity: 9.81

        calibration:
            lidar_to_imu:
                [
                    1.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    1.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    1.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    1.0,
                ]

        frontend:
            fusion_opti_iters: 10
            fusion_method: TightCouplingOptimization # LooseCoupling, TightCouplingKF, TightCouplingOptimization

            registration_and_searcher_mode: PointToPlane_KdTree
            feature:
                planar_voxel_filter_size: 0.5
            registration:
                local_map_size: 0
                optimization_iter_num: 8
                point_to_planar_thres: 0.1
                position_converge_thres: 0.005
                rotation_converge_thres: 0.005
                local_map_cloud_filter_size: 0.5
                keyframe_delta_distance: 0.0
                keyframe_delta_rotation: 0.0
